### ISSUE TITLE
Inconsistency between release zip and Git repo

### ISSUE THREAD

**Issue by Si-Shi** [Triangle-Modeling-and-Analytics/TRMG2#277]
This issue is raised by one of the consultants who just got G2 v1.2. He asked why there is differences between zip release and git repo. There is a docs folder in repo but not in release, while the release has a trmg2.scenario file but repo doesn't.  Is it a real issue or something intended but needs to be documented. Thoughts?

**Comment by dkyleward** [comment]
This is by design. The repo contains the docs folder because that is the website (hosted by GitHub). However, it is not required for the model. The release zip that we send out is just the model. Also, the scenario file is not version controlled, but for convenience, I create one in the release. These are all designed to make the model 'just work'.
